### ISSUE TITLE
Error on "debug mpls ldp" configuration

### ISSUE THREAD

**Issue by MHZarei** [rwestphal/quagga-ldpd#1]
Hi,
I configure and install quagga-ldpd with --enable-mpls and --enable-ldpd parameter, but ldpd can't run with these configuration:

```
debug mpls ldp messages recv
debug mpls ldp messages sent
debug mpls ldp zebra
```

The error:

```
$ sudo ldpd 
*** Error reading config: There is no such command.
*** Error occured processing line 8, below:
debug mpls ldp messages recv
```

I'm using Debian 7.1 with kernel 4.6.3.

**Comment by rwestphal** [comment]
You are probably running an old  version of ldpd, these commands should work. Please make sure that you updated ldpd properly.

**Comment by MHZarei** [comment]
Quagga version in vtysh:

```
# show version 
Quagga 1.0.20160315 ().
Copyright 1996-2005 Kunihiro Ishiguro, et al.
configured with:
    --enable-mpls --enable-ldpd --sysconfdir=/etc/quagga --localstatedir=/var/run/
```

And that is source git log:

```
$ git log 
commit 7481789361dcdef4c7af73c10e2fb1e8479646ef
Author: Renato Westphal <renato@opensourcerouting.org>
Date:   Wed Jun 22 09:59:28 2016 -0300

    ldpd: cap'n proto support (wip)

commit 86ffa94736fd85517df3316616b538ba96a86d98
Author: Renato Westphal <renato@opensourcerouting.org>
Date:   Thu Jun 2 08:28:15 2016 -0300

    mpls: add support to the OpenBSD kernel

```

I think it is last update of quagga-ldp.

**Comment by rwestphal** [comment]
That's one week old. I rebased the ldpd-port branch yesterday, so delete your local branch and fetch it again to get the latest updates.

Or do something like this:
$ git reset --hard HEAD~50
$ git pull

BTW, I'm constantly rebasing this branch, so plain git pull is not your friend :)

**Comment by MHZarei** [comment]
This work for me.
Thanks.

**Comment by jpazevedo92** [comment]
Hello i'm João
I'm currently try to install zebra with ldpd configuration in ubuntu 18.04 lts with kernel version 5.3.0-51-generic and keeping appears that error to me. Someone please can help?

when i run this zebra -d -f /etc/quagga/zebra.conf ldpd -d -f /etc/quagga/ldpd.conf
Returns the following error: 

*** Error reading config: There is no such command.
*** Error occured processing line 15, below:
mpls ldp

**Comment by rwestphal** [comment]
@jpazevedo92 this repository is deprecated. Please use FRRouting instead (https://github.com/FRRouting/frr).

**Comment by jpazevedo92** [comment]
Thanks @rwestphal! do you know if the examples you have here are compatible with FRR?
