### ISSUE TITLE
Support for VPLS ?

### ISSUE THREAD

**Issue by dipjyoti** [rwestphal/quagga-ldpd#4]
Does quagga-ldps support  VPLS with linux kernel ??

**Comment by ne-vlezay80** [comment]
See: https://github.com/rwestphal/quagga-ldpd/wiki/ldpd-basic-test-setup

**Comment by rwestphal** [comment]
The Linux kernel doesn't support pseudowire interfaces at this moment, but I know someone who is working on this so you can expect some updates in the following weeks. You can also try OpenBSD which supports VPLS out of the box (both data and control plane).

**Comment by dipjyoti** [comment]
Thanks for the update. I will try OpenBSD
